name: cdlp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9 # Using flutter_riverpod for Flutter
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
